apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /(api/v1)/resources(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: resource-service
                port:
                  number: 8090
          - path: /(api/v1)/songs(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: song-service
                port:
                  number: 8091