services:
  resource-db:
    extends:
      file: common.yaml
      service: postgres-base
    environment:
      POSTGRES_DB: resource_db
      POSTGRES_USER: ${RESOURCE_DB_USER}
      POSTGRES_PASSWORD: ${RESOURCE_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts/resource-db:/docker-entrypoint-initdb.d:ro

  song-db:
    extends:
      file: common.yaml
      service: postgres-base
    environment:
      POSTGRES_DB: song_db
      POSTGRES_USER: ${SONG_DB_USER}
      POSTGRES_PASSWORD: ${SONG_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./init-scripts/song-db:/docker-entrypoint-initdb.d:ro

  resource-service:
    depends_on:
      resource-db:
        condition: service_healthy
    build:
      context: .
      dockerfile: resource-service/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_DB_URL}
      SPRING_DATASOURCE_USER: ${RESOURCE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${RESOURCE_DB_PASSWORD}
    ports:
      - "8090:8090"

  song-service:
    depends_on:
      song-db:
        condition: service_healthy
    build:
      context: .
      dockerfile: song-service/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: ${SONG_DB_URL}
      SPRING_DATASOURCE_USER: ${SONG_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${SONG_DB_PASSWORD}
    ports:
      - "8091:8091"
