apiVersion: v1
kind: Service
metadata:
  name: resource-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: resource-service
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: {{ .Values.resourceServicePort }}
