server:
  port: 8085
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: resource-service
              uri: lb://RESOURCE-SERVICE
              predicates:
                - Path=/resources/**,/resources
            - id: song-service
              uri: lb://SONG-SERVICE
              predicates:
                - Path=/songs/**,/songs
eureka:
  client:
    service-url:
      defaultZone: "${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}"