apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-db-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mp3-storage.labels" . | nindent 4 }}
data:
  postgres-db: resource_db
  init.sql: |
    CREATE TABLE resources (
        id BIGSERIAL PRIMARY KEY,
        audio_data BYTEA NOT NULL
    );