apiVersion: v1
kind: Service
metadata:
  name: resource-db-ext
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: resource-db
  ports:
    - port: 5433
      targetPort: 5432