apiVersion: v1
kind: Service
metadata:
  name: resource-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: resource-service
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-service
  namespace: k8s-program
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: resource-service
  template:
    metadata:
      labels:
        app: resource-service
    spec:
      containers:
        - name: resource-service
          image: resource-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: resource-service-config
          env:
            - name: SPRING_DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-password
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 3
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8090
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8090
            periodSeconds: 5
