apiVersion: v1
kind: Service
metadata:
  name: song-db
  namespace: k8s-program
spec:
  clusterIP: None
  selector:
    app: song-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: song-db
  namespace: k8s-program
spec:
  serviceName: song-db
  replicas: 1
  selector:
    matchLabels:
      app: song-db
  template:
    metadata:
      labels:
        app: song-db
    spec:
      containers:
        - name: song-db
          image: postgres:18-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: song_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 256Mi