apiVersion: v1
kind: PersistentVolume
metadata:
  name: song-service-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/song-service