server:
  port: 8090
song-service:
  client:
    base-url: "http://localhost:8091"
spring:
  application:
    name: resource-service
  datasource:
    url: jdbc:postgresql://localhost:5432/resource-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
